# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/configuration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from distantrs.proto.google.devtools.resultstore.v2 import common_pb2 as google_dot_devtools_dot_resultstore_dot_v2_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/devtools/resultstore/v2/configuration.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n2google/devtools/resultstore/v2/configuration.proto\x12\x1egoogle.devtools.resultstore.v2\x1a+google/devtools/resultstore/v2/common.proto\"\x8e\x03\n\rConfiguration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12<\n\x02id\x18\x02 \x01(\x0b\x32\x30.google.devtools.resultstore.v2.Configuration.Id\x12K\n\x11status_attributes\x18\x03 \x01(\x0b\x32\x30.google.devtools.resultstore.v2.StatusAttributes\x12Y\n\x18\x63onfiguration_attributes\x18\x05 \x01(\x0b\x32\x37.google.devtools.resultstore.v2.ConfigurationAttributes\x12<\n\nproperties\x18\x06 \x03(\x0b\x32(.google.devtools.resultstore.v2.Property\x12\x14\n\x0c\x64isplay_name\x18\x08 \x01(\t\x1a\x35\n\x02Id\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x18\n\x10\x63onfiguration_id\x18\x02 \x01(\t\"&\n\x17\x43onfigurationAttributes\x12\x0b\n\x03\x63pu\x18\x01 \x01(\tBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
  ,
  dependencies=[google_dot_devtools_dot_resultstore_dot_v2_dot_common__pb2.DESCRIPTOR,])




_CONFIGURATION_ID = _descriptor.Descriptor(
  name='Id',
  full_name='google.devtools.resultstore.v2.Configuration.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='invocation_id', full_name='google.devtools.resultstore.v2.Configuration.Id.invocation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration_id', full_name='google.devtools.resultstore.v2.Configuration.Id.configuration_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=530,
)

_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='google.devtools.resultstore.v2.Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.resultstore.v2.Configuration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='google.devtools.resultstore.v2.Configuration.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_attributes', full_name='google.devtools.resultstore.v2.Configuration.status_attributes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='configuration_attributes', full_name='google.devtools.resultstore.v2.Configuration.configuration_attributes', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='properties', full_name='google.devtools.resultstore.v2.Configuration.properties', index=4,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='google.devtools.resultstore.v2.Configuration.display_name', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGURATION_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=530,
)


_CONFIGURATIONATTRIBUTES = _descriptor.Descriptor(
  name='ConfigurationAttributes',
  full_name='google.devtools.resultstore.v2.ConfigurationAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='google.devtools.resultstore.v2.ConfigurationAttributes.cpu', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=570,
)

_CONFIGURATION_ID.containing_type = _CONFIGURATION
_CONFIGURATION.fields_by_name['id'].message_type = _CONFIGURATION_ID
_CONFIGURATION.fields_by_name['status_attributes'].message_type = google_dot_devtools_dot_resultstore_dot_v2_dot_common__pb2._STATUSATTRIBUTES
_CONFIGURATION.fields_by_name['configuration_attributes'].message_type = _CONFIGURATIONATTRIBUTES
_CONFIGURATION.fields_by_name['properties'].message_type = google_dot_devtools_dot_resultstore_dot_v2_dot_common__pb2._PROPERTY
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION
DESCRIPTOR.message_types_by_name['ConfigurationAttributes'] = _CONFIGURATIONATTRIBUTES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _CONFIGURATION_ID,
    '__module__' : 'google.devtools.resultstore.v2.configuration_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.Configuration.Id)
    })
  ,
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'google.devtools.resultstore.v2.configuration_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.Configuration)
  })
_sym_db.RegisterMessage(Configuration)
_sym_db.RegisterMessage(Configuration.Id)

ConfigurationAttributes = _reflection.GeneratedProtocolMessageType('ConfigurationAttributes', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATIONATTRIBUTES,
  '__module__' : 'google.devtools.resultstore.v2.configuration_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.ConfigurationAttributes)
  })
_sym_db.RegisterMessage(ConfigurationAttributes)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
