# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/coverage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/devtools/resultstore/v2/coverage.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/devtools/resultstore/v2/coverage.proto\x12\x1egoogle.devtools.resultstore.v2\"B\n\x0cLineCoverage\x12\x1a\n\x12instrumented_lines\x18\x01 \x01(\x0c\x12\x16\n\x0e\x65xecuted_lines\x18\x02 \x01(\x0c\"c\n\x0e\x42ranchCoverage\x12\x16\n\x0e\x62ranch_present\x18\x01 \x01(\x0c\x12\x18\n\x10\x62ranches_in_line\x18\x02 \x03(\x05\x12\x10\n\x08\x65xecuted\x18\x03 \x01(\x0c\x12\r\n\x05taken\x18\x04 \x01(\x0c\"\xaa\x01\n\x0c\x46ileCoverage\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x43\n\rline_coverage\x18\x02 \x01(\x0b\x32,.google.devtools.resultstore.v2.LineCoverage\x12G\n\x0f\x62ranch_coverage\x18\x03 \x01(\x0b\x32..google.devtools.resultstore.v2.BranchCoverage\"V\n\x0e\x41\x63tionCoverage\x12\x44\n\x0e\x66ile_coverages\x18\x02 \x03(\x0b\x32,.google.devtools.resultstore.v2.FileCoverage\"Y\n\x11\x41ggregateCoverage\x12\x44\n\x0e\x66ile_coverages\x18\x01 \x03(\x0b\x32,.google.devtools.resultstore.v2.FileCoverageBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
)




_LINECOVERAGE = _descriptor.Descriptor(
  name='LineCoverage',
  full_name='google.devtools.resultstore.v2.LineCoverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrumented_lines', full_name='google.devtools.resultstore.v2.LineCoverage.instrumented_lines', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executed_lines', full_name='google.devtools.resultstore.v2.LineCoverage.executed_lines', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=147,
)


_BRANCHCOVERAGE = _descriptor.Descriptor(
  name='BranchCoverage',
  full_name='google.devtools.resultstore.v2.BranchCoverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch_present', full_name='google.devtools.resultstore.v2.BranchCoverage.branch_present', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branches_in_line', full_name='google.devtools.resultstore.v2.BranchCoverage.branches_in_line', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='executed', full_name='google.devtools.resultstore.v2.BranchCoverage.executed', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taken', full_name='google.devtools.resultstore.v2.BranchCoverage.taken', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=248,
)


_FILECOVERAGE = _descriptor.Descriptor(
  name='FileCoverage',
  full_name='google.devtools.resultstore.v2.FileCoverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='google.devtools.resultstore.v2.FileCoverage.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_coverage', full_name='google.devtools.resultstore.v2.FileCoverage.line_coverage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branch_coverage', full_name='google.devtools.resultstore.v2.FileCoverage.branch_coverage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=421,
)


_ACTIONCOVERAGE = _descriptor.Descriptor(
  name='ActionCoverage',
  full_name='google.devtools.resultstore.v2.ActionCoverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_coverages', full_name='google.devtools.resultstore.v2.ActionCoverage.file_coverages', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=509,
)


_AGGREGATECOVERAGE = _descriptor.Descriptor(
  name='AggregateCoverage',
  full_name='google.devtools.resultstore.v2.AggregateCoverage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_coverages', full_name='google.devtools.resultstore.v2.AggregateCoverage.file_coverages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=600,
)

_FILECOVERAGE.fields_by_name['line_coverage'].message_type = _LINECOVERAGE
_FILECOVERAGE.fields_by_name['branch_coverage'].message_type = _BRANCHCOVERAGE
_ACTIONCOVERAGE.fields_by_name['file_coverages'].message_type = _FILECOVERAGE
_AGGREGATECOVERAGE.fields_by_name['file_coverages'].message_type = _FILECOVERAGE
DESCRIPTOR.message_types_by_name['LineCoverage'] = _LINECOVERAGE
DESCRIPTOR.message_types_by_name['BranchCoverage'] = _BRANCHCOVERAGE
DESCRIPTOR.message_types_by_name['FileCoverage'] = _FILECOVERAGE
DESCRIPTOR.message_types_by_name['ActionCoverage'] = _ACTIONCOVERAGE
DESCRIPTOR.message_types_by_name['AggregateCoverage'] = _AGGREGATECOVERAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LineCoverage = _reflection.GeneratedProtocolMessageType('LineCoverage', (_message.Message,), {
  'DESCRIPTOR' : _LINECOVERAGE,
  '__module__' : 'google.devtools.resultstore.v2.coverage_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.LineCoverage)
  })
_sym_db.RegisterMessage(LineCoverage)

BranchCoverage = _reflection.GeneratedProtocolMessageType('BranchCoverage', (_message.Message,), {
  'DESCRIPTOR' : _BRANCHCOVERAGE,
  '__module__' : 'google.devtools.resultstore.v2.coverage_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.BranchCoverage)
  })
_sym_db.RegisterMessage(BranchCoverage)

FileCoverage = _reflection.GeneratedProtocolMessageType('FileCoverage', (_message.Message,), {
  'DESCRIPTOR' : _FILECOVERAGE,
  '__module__' : 'google.devtools.resultstore.v2.coverage_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.FileCoverage)
  })
_sym_db.RegisterMessage(FileCoverage)

ActionCoverage = _reflection.GeneratedProtocolMessageType('ActionCoverage', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONCOVERAGE,
  '__module__' : 'google.devtools.resultstore.v2.coverage_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.ActionCoverage)
  })
_sym_db.RegisterMessage(ActionCoverage)

AggregateCoverage = _reflection.GeneratedProtocolMessageType('AggregateCoverage', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATECOVERAGE,
  '__module__' : 'google.devtools.resultstore.v2.coverage_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.AggregateCoverage)
  })
_sym_db.RegisterMessage(AggregateCoverage)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
