# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/file_set.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from distantrs.proto.google.devtools.resultstore.v2 import file_pb2 as google_dot_devtools_dot_resultstore_dot_v2_dot_file__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/devtools/resultstore/v2/file_set.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n-google/devtools/resultstore/v2/file_set.proto\x12\x1egoogle.devtools.resultstore.v2\x1a)google/devtools/resultstore/v2/file.proto\"\xc9\x01\n\x07\x46ileSet\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x36\n\x02id\x18\x02 \x01(\x0b\x32*.google.devtools.resultstore.v2.FileSet.Id\x12\x11\n\tfile_sets\x18\x03 \x03(\t\x12\x33\n\x05\x66iles\x18\x04 \x03(\x0b\x32$.google.devtools.resultstore.v2.File\x1a\x30\n\x02Id\x12\x15\n\rinvocation_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66ile_set_id\x18\x02 \x01(\tBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
  ,
  dependencies=[google_dot_devtools_dot_resultstore_dot_v2_dot_file__pb2.DESCRIPTOR,])




_FILESET_ID = _descriptor.Descriptor(
  name='Id',
  full_name='google.devtools.resultstore.v2.FileSet.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='invocation_id', full_name='google.devtools.resultstore.v2.FileSet.Id.invocation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_set_id', full_name='google.devtools.resultstore.v2.FileSet.Id.file_set_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=326,
)

_FILESET = _descriptor.Descriptor(
  name='FileSet',
  full_name='google.devtools.resultstore.v2.FileSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google.devtools.resultstore.v2.FileSet.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='google.devtools.resultstore.v2.FileSet.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_sets', full_name='google.devtools.resultstore.v2.FileSet.file_sets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='files', full_name='google.devtools.resultstore.v2.FileSet.files', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FILESET_ID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=326,
)

_FILESET_ID.containing_type = _FILESET
_FILESET.fields_by_name['id'].message_type = _FILESET_ID
_FILESET.fields_by_name['files'].message_type = google_dot_devtools_dot_resultstore_dot_v2_dot_file__pb2._FILE
DESCRIPTOR.message_types_by_name['FileSet'] = _FILESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileSet = _reflection.GeneratedProtocolMessageType('FileSet', (_message.Message,), {

  'Id' : _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
    'DESCRIPTOR' : _FILESET_ID,
    '__module__' : 'google.devtools.resultstore.v2.file_set_pb2'
    # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.FileSet.Id)
    })
  ,
  'DESCRIPTOR' : _FILESET,
  '__module__' : 'google.devtools.resultstore.v2.file_set_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.FileSet)
  })
_sym_db.RegisterMessage(FileSet)
_sym_db.RegisterMessage(FileSet.Id)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
