# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/devtools/resultstore/v2/resultstore_file_download.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from distantrs.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from distantrs.proto.google.api import client_pb2 as google_dot_api_dot_client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='google/devtools/resultstore/v2/resultstore_file_download.proto',
  package='google.devtools.resultstore.v2',
  syntax='proto3',
  serialized_options=b'\n\"com.google.devtools.resultstore.v2P\001ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstore',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>google/devtools/resultstore/v2/resultstore_file_download.proto\x12\x1egoogle.devtools.resultstore.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\"]\n\x0eGetFileRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x13\n\x0bread_offset\x18\x02 \x01(\x03\x12\x12\n\nread_limit\x18\x03 \x01(\x03\x12\x15\n\rarchive_entry\x18\x04 \x01(\t\"\x1f\n\x0fGetFileResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"a\n\x12GetFileTailRequest\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x13\n\x0bread_offset\x18\x02 \x01(\x03\x12\x12\n\nread_limit\x18\x03 \x01(\x03\x12\x15\n\rarchive_entry\x18\x04 \x01(\t\"#\n\x13GetFileTailResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x8a\x03\n\x17ResultStoreFileDownload\x12\x86\x01\n\x07GetFile\x12..google.devtools.resultstore.v2.GetFileRequest\x1a/.google.devtools.resultstore.v2.GetFileResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v2/{uri=file/*}0\x01\x12\x95\x01\n\x0bGetFileTail\x12\x32.google.devtools.resultstore.v2.GetFileTailRequest\x1a\x33.google.devtools.resultstore.v2.GetFileTailResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v2/{uri=file/tail/*}\x1aN\xca\x41\x1aresultstore.googleapis.com\xd2\x41.https://www.googleapis.com/auth/cloud-platformBq\n\"com.google.devtools.resultstore.v2P\x01ZIgoogle.golang.org/genproto/googleapis/devtools/resultstore/v2;resultstoreb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_api_dot_client__pb2.DESCRIPTOR,])




_GETFILEREQUEST = _descriptor.Descriptor(
  name='GetFileRequest',
  full_name='google.devtools.resultstore.v2.GetFileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='google.devtools.resultstore.v2.GetFileRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_offset', full_name='google.devtools.resultstore.v2.GetFileRequest.read_offset', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_limit', full_name='google.devtools.resultstore.v2.GetFileRequest.read_limit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='archive_entry', full_name='google.devtools.resultstore.v2.GetFileRequest.archive_entry', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=246,
)


_GETFILERESPONSE = _descriptor.Descriptor(
  name='GetFileResponse',
  full_name='google.devtools.resultstore.v2.GetFileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.devtools.resultstore.v2.GetFileResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=279,
)


_GETFILETAILREQUEST = _descriptor.Descriptor(
  name='GetFileTailRequest',
  full_name='google.devtools.resultstore.v2.GetFileTailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='google.devtools.resultstore.v2.GetFileTailRequest.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_offset', full_name='google.devtools.resultstore.v2.GetFileTailRequest.read_offset', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_limit', full_name='google.devtools.resultstore.v2.GetFileTailRequest.read_limit', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='archive_entry', full_name='google.devtools.resultstore.v2.GetFileTailRequest.archive_entry', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=378,
)


_GETFILETAILRESPONSE = _descriptor.Descriptor(
  name='GetFileTailResponse',
  full_name='google.devtools.resultstore.v2.GetFileTailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='google.devtools.resultstore.v2.GetFileTailResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=415,
)

DESCRIPTOR.message_types_by_name['GetFileRequest'] = _GETFILEREQUEST
DESCRIPTOR.message_types_by_name['GetFileResponse'] = _GETFILERESPONSE
DESCRIPTOR.message_types_by_name['GetFileTailRequest'] = _GETFILETAILREQUEST
DESCRIPTOR.message_types_by_name['GetFileTailResponse'] = _GETFILETAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetFileRequest = _reflection.GeneratedProtocolMessageType('GetFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILEREQUEST,
  '__module__' : 'google.devtools.resultstore.v2.resultstore_file_download_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.GetFileRequest)
  })
_sym_db.RegisterMessage(GetFileRequest)

GetFileResponse = _reflection.GeneratedProtocolMessageType('GetFileResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFILERESPONSE,
  '__module__' : 'google.devtools.resultstore.v2.resultstore_file_download_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.GetFileResponse)
  })
_sym_db.RegisterMessage(GetFileResponse)

GetFileTailRequest = _reflection.GeneratedProtocolMessageType('GetFileTailRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETFILETAILREQUEST,
  '__module__' : 'google.devtools.resultstore.v2.resultstore_file_download_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.GetFileTailRequest)
  })
_sym_db.RegisterMessage(GetFileTailRequest)

GetFileTailResponse = _reflection.GeneratedProtocolMessageType('GetFileTailResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETFILETAILRESPONSE,
  '__module__' : 'google.devtools.resultstore.v2.resultstore_file_download_pb2'
  # @@protoc_insertion_point(class_scope:google.devtools.resultstore.v2.GetFileTailResponse)
  })
_sym_db.RegisterMessage(GetFileTailResponse)


DESCRIPTOR._options = None

_RESULTSTOREFILEDOWNLOAD = _descriptor.ServiceDescriptor(
  name='ResultStoreFileDownload',
  full_name='google.devtools.resultstore.v2.ResultStoreFileDownload',
  file=DESCRIPTOR,
  index=0,
  serialized_options=b'\312A\032resultstore.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platform',
  create_key=_descriptor._internal_create_key,
  serialized_start=418,
  serialized_end=812,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='google.devtools.resultstore.v2.ResultStoreFileDownload.GetFile',
    index=0,
    containing_service=None,
    input_type=_GETFILEREQUEST,
    output_type=_GETFILERESPONSE,
    serialized_options=b'\202\323\344\223\002\022\022\020/v2/{uri=file/*}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFileTail',
    full_name='google.devtools.resultstore.v2.ResultStoreFileDownload.GetFileTail',
    index=1,
    containing_service=None,
    input_type=_GETFILETAILREQUEST,
    output_type=_GETFILETAILRESPONSE,
    serialized_options=b'\202\323\344\223\002\027\022\025/v2/{uri=file/tail/*}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESULTSTOREFILEDOWNLOAD)

DESCRIPTOR.services_by_name['ResultStoreFileDownload'] = _RESULTSTOREFILEDOWNLOAD

# @@protoc_insertion_point(module_scope)
