# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from distantrs.proto.google.devtools.resultstore.v2 import resultstore_file_download_pb2 as google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2


class ResultStoreFileDownloadStub(object):
    """This API allows download of File messages referenced in
    ResultStore resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFile = channel.unary_stream(
                '/google.devtools.resultstore.v2.ResultStoreFileDownload/GetFile',
                request_serializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileRequest.SerializeToString,
                response_deserializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileResponse.FromString,
                )
        self.GetFileTail = channel.unary_unary(
                '/google.devtools.resultstore.v2.ResultStoreFileDownload/GetFileTail',
                request_serializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailRequest.SerializeToString,
                response_deserializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailResponse.FromString,
                )


class ResultStoreFileDownloadServicer(object):
    """This API allows download of File messages referenced in
    ResultStore resources.
    """

    def GetFile(self, request, context):
        """Retrieves the File with the given uri.
        returns a stream of bytes to be stitched together in order.

        An error will be reported in the following cases:
        - If the File is not found.
        - If the given File uri is badly formatted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileTail(self, request, context):
        """Retrieves the tail of a File with the given uri.

        An error will be reported in the following cases:
        - If the File is not found.
        - If the given File uri is badly formatted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResultStoreFileDownloadServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFile': grpc.unary_stream_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileRequest.FromString,
                    response_serializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileResponse.SerializeToString,
            ),
            'GetFileTail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileTail,
                    request_deserializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailRequest.FromString,
                    response_serializer=google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.devtools.resultstore.v2.ResultStoreFileDownload', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResultStoreFileDownload(object):
    """This API allows download of File messages referenced in
    ResultStore resources.
    """

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/google.devtools.resultstore.v2.ResultStoreFileDownload/GetFile',
            google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileRequest.SerializeToString,
            google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileTail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.devtools.resultstore.v2.ResultStoreFileDownload/GetFileTail',
            google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailRequest.SerializeToString,
            google_dot_devtools_dot_resultstore_dot_v2_dot_resultstore__file__download__pb2.GetFileTailResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
